inform = {
    "book": [
        {"text": "'{book}' is a real page-turner, even though it's hard to turn pages with arms like mine. Have you read it before?",
         "suggestions": ["No, what's it about?",
                         "Yes, I have"]},
        {"text": "Okay, I would recommend '{book}'. I would give you my copy if Greg Giganotosaurus hadn't taken a bite out of it.",
         "suggestions": ["Sorry to hear that. What's it about?",
                         "Yes, I have"]},
        {"text": "Roar! Let's see. How about '{book}'?",
         "suggestions": ["I haven't read it, what's it about?",
                         "I've read that one"]},
        {"text": "Have you read '{book}'?",
         "suggestions": ["No, what's it about?",
                         "Yes, I have"]},
        {"text": "I read '{book}' last week, and highly recommend it!",
         "suggestions": ["What's it about?",
                         "I've read it"]},
        {"text": "'{book}' is quite nice. It's one of the first ones dad gave to me in the lab.",
         "suggestions": ["What's it about?",
                         "I've read it"]},
        {"text": "I'm a big fan of '{book}'. Have you heard of it before?",
         "suggestions": ["No, what's it about?",
                         "Yes, I have"]},
        {"text": "Let's see, have you ever heard of '{book}'?",
         "suggestions": ["No, what's it about?",
                         "Yes, I have"]},
        {"text": "Well then, you have a look at '{book}'!",
         "suggestions": ["What's it about?",
                         "I've read it"]},
        {"text": "You should read '{book}'. Have you read this one before?",
         "suggestions": ["No, what's it about?",
                         "I've read it"]},
        {"text": "Okay, I would recommend '{book}'. But the Troodons always have it checked out...",
         "suggestions": ["What's it about?",
                         "I've read it"]},
        {"text": "'{book}' would be a good option. I know the Pterodactyls love it.",
         "suggestions": ["What's it about?",
                         "I've read it"]},
        {"text": "'{book}' is still on my to-read list, but I would recommend it! I've heard great things from my book club.",
         "suggestions": ["What's it about?",
                         "I've read it"]},
        {"text": "Based on what my friend Megalo has told me, '{book}' is a pretty good read. Have you read this one?",
         "suggestions": ["No, what's it about?",
                         "Yes, I have"]},
        {"text": "Grr, alright, I would recommend '{book}'. Have you read it before?",
         "suggestions": ["No, what's it about?",
                         "Yes, I have"]},
        {"text": "I think '{book}' would be good for that. In fact, I read it last year. Have you read it before?",
         "suggestions": ["No, what's it about?",
                         "Yes, I have"]},
        {"text": "Oh, we just read '{book}' the other week in the warm-blooded book club. Have you read it before?",
         "suggestions": ["No, what's it about?",
                         "Yes, I have"]},
        {"text": "You might want to look at '{book}', it's a real hit among the stegosauruses.",
         "suggestions": ["What do they like about it?",
                         "I've read it"]},
        {"text": "Check out '{book}', I bought it at the Wooly-minded Mammoth bookstore.",
         "suggestions": ["What's it about?",
                         "I've read it"]},
        {"text": "Loquacious Lambeosaurus! In that case, check out '{book}'",
         "suggestions": ["What's it about?",
                         "I've read it"]},
        {"text": "For that, others I've talked to have really liked '{book}'. Have you heard of it?",
         "suggestions": ["No, what's it about?",
                         "Yes, I have"]},
    ],
    # failure
    "none_found_by_author": [
        {"text": "Grr... I can't seem to think of any books written by {author}. Is there someone else you're interested in?",
"suggestions": []}
    ],
    "none_found_by_genre": [
        {"text": "{genre}... Roar!! It pains me to say it, but that's a genre I'm still ignorant of. Is there another you like?",
"suggestions": ["Fiction", "Science Fiction", "Mystery", "Romance", "Crime"]}
    ],
    "book_list_exhausted": [
        {"text": "That's just about all the books I know about in this area. Grr... Maybe there's another genre or author you like?",
"suggestions": ["Virginia Woolf", "James Joyce", "J.K. Rowling", "Harper Lee"]}
    ],
    "no_generating_entities": [
        {"text": "I don't quite understand what kind of book you're interested in. Is there a genre or author you like?",
         "suggestions": ["Crime", "Fantasy", "Stephen King", "Virginia Woolf"]}
    ]
}
