book = [
"Have you read \"{book}\"?",
"I read \"{book}\" last week, and highly recommend it!",
"\"{book}\" is quite nice. My friend B. Excelsus told me about it last week.",
"I'm a big fan of \"{book}\". Have you heard of it before?",
"Let's see, have you ever heard of \"{book}\"?",
"Well then, you have a look at \"{book}\"!",
"You should read \"{book}\". Have you read this one before?",
"Let's see. How about \"{book}\"?",
"Okay, I would recommend \"{book}\".",
"\"{book}\" would be a good option. Have you read this one before?",
"\"{book}\" is still on my to-read list, but I would recommend it! I've heard great things from my book club.",
"Based on what a good friend has told me, \"{book}\" is a pretty good read. Have you read this one?",
"Hmm, alright, I would recommend \"{book}\". Have you read it before?",
"I think \"{book}\" would be good for that. In fact, I read it last year. Have you read it before?",
"Oh, \"{book}\" has been a hit among the other dinosaurs. Have you read it before?",
"\"{book}\" is a real page-turner, even though it's difficult to turn pages with little arms. Have you read it before?",
"You might want to look at \"{book}\", it's a real hit among the stegasauruses.",
]

# failure
none_found_by_author = [
"I can't seem to think of any books written by {author}. Is there someone else you're interested in?"
]

none_found_by_genre = [
"{genre}... Unfortunately, that's a genre I'm still ignorant of. Is there another you like?",
"Never heard of it"
]

book_list_exhausted = [
"That's just about all the books I know about in this area. Maybe there's another genre or author you like?"
]

no_generating_entities = [
"I don't quite understand what kind of book you're interested in. Is there a genre or author you like?"
]
