title = [
"""The book is called '{title}'.""",
"""It's called '{title}'.""",
"""The name of the book is '{title}'.""",
"""'{title}'.""",
"""'{title}'.""",
"""'{title}'.""",
]

author = [
"""{author} wrote it.""",
"""It's by {author}.""",
"""{author}.""",
"""{author}.""",
"""{author}.""",
]

summary = [
"""Here's how my friend {friend} summarized it once:\n\n{summary}""",
"""{friend}'s read this one. This is what they had to say:\n\n{summary}""",
"""{friend} wrote me about this:\n\n{summary}""",
]

rating = [
"""The club's consensus was around {rating} stars out of 5.""",
]

# failure
no_current_book = [
"""Which one?""",
"""Which book are you referring to?""",
"""Which book are you talking about?""",
]

no_reviews = [
"""I don't know too much about this one, actually.""",
"""I don't know too much about this one. Maybe there's another book you'd like to hear about?""",
]
